version: '3.8'
services:
  postgres:
    image: 'postgres:15.5'
    environment:
      - 'POSTGRES_DB=elevate'
      - 'POSTGRES_PASSWORD=elevate'
      - 'POSTGRES_USER=elevate'
    ports:
      - '15432:5432'

#  postgres-test:
#    image: 'postgres:15.5'
#    environment:
#      - 'POSTGRES_DB=elevate_test'
#      - 'POSTGRES_PASSWORD=elevate_test'
#      - 'POSTGRES_USER=elevate_test'
#    ports:
#      - '15432:5432'
#
#  app-test:
#    build:
#      context: .
#      dockerfile: Dockerfile.test
#    depends_on:
#      - postgres-test
#  app:
#    build: .
#    environment:
#      JDBC_DATABASE_URL: 'jdbc:postgresql://postgres:5432/elevate'
#      JDBC_DATABASE_USERNAME: elevate
#      JDBC_DATABASE_PASSWORD: elevate
#    depends_on:
#      - postgres
#    ports:
#      - "3000:3000"
