version: '3.8'
services:
  postgres:
    image: 'postgres:15.5'
    environment:
      - 'POSTGRES_DB=elevate'
      - 'POSTGRES_PASSWORD=elevate'
      - 'POSTGRES_USER=elevate'
    ports:
      - '15432:5432'

  java:
    image: 'eclipse-temurin:17.0.9_9-jdk-focal'
    volumes:
      - .:/app
    working_dir: /app

  gradle:
    image: 'gradle:jdk17-focal'
    volumes:
      - .:/home/gradle/project
      - gradle-cache:/home/gradle/.gradle
    working_dir: /home/gradle/project
    command: tail -f /dev/null

#  app:
#    build: .
#    environment:
#      JDBC_DATABASE_URL: 'jdbc:postgresql://postgres:5432/elevate'
#      JDBC_DATABASE_USERNAME: elevate
#      JDBC_DATABASE_PASSWORD: elevate
#    depends_on:
#      - postgres
#    ports:
#      - "3000:3000"
volumes:
  gradle-cache:
