# Dockerfile.test
FROM eclipse-temurin:17.0.9_9-jdk-focal
COPY . /app
WORKDIR /app
RUN ./gradlew build -x test # Build without running tests

# Define the command to run tests when the container starts
CMD ["./gradlew", "test"]
